### ISSUE TITLE
问一个弱智的小白问题呀。怎么使用这个

### ISSUE THREAD

**Issue by yfming93** [cnych/sinaimgmover#1]
mac 环境下，需要安装什么环境吗。我下载 linux_amd64 release包切换到对应的文件夹执行 mover -h 出现如下。
$ cd /Users/mingo/Desktop/linux_amd64

# mingo @ 192 in ~/Desktop/linux_amd64 [16:59:33]
$ mover -h
zsh: command not found: mover

**Comment by cnych** [comment]
呃，你MAC环境肯定是下载`darwin_amd64.zip`这个包呀，下载下来解压后把里面的文件重命名为 mover 就可以了。

**Comment by yfming93** [comment]
下载 darwin_amd64 也是运行不了。
# mingo @ 192 in ~/Desktop/darwin_amd64 [17:28:09]
$ mover -h
zsh: command not found: mover

**Comment by yfming93** [comment]
我已经会使用了。解压后。把 mover 复制到 home 目录。然后使用绝对路径就阔以了。感谢指教呀。
/Users/mingo/mover -h

**Comment by yfming93** [comment]
感谢。博客图片已经从微博图床迁移到阿里云OSS了。

**Comment by yfming93** [comment]
我补充一个小技巧。这个脚本对 .md 后缀文件生效，对.markdown后缀文件不行。直接把 .markdown 后缀文件改成 .md 后缀文件也是一样的哈
